# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: Synapse-Indexer

field_selection:
  transaction_fields:
    - hash

networks:
- id: 10143
  start_block: 42500000
  contracts:
  - name: Magma
    address:
    - 0x2c9C959516e9AAEdB2C748224a41249202ca8BE7
    handler: src/EventHandlers.ts
    events:
    - event: Deposit(address indexed depositor, uint256 indexed amount, uint256 gMonMinted, uint256 indexed referralId)
    - event: Withdraw(address indexed withdrawer, uint256 indexed amount, uint256 gMonBurned)

  - name: Kintsu
    address:
    - 0xe1d2439b75fb9746E7Bc6cB777Ae10AA7f7ef9c5
    handler: src/EventHandlers.ts
    events:
    - event: Transfer(address indexed from, address indexed to, uint256 value)

  - name: Pancake
    address:
    - 0x36da083016CF35ED986f35F539C0404C00306988
    handler: src/EventHandlers.ts
    events:
    - event: Swap(address indexed sender, address indexed recipient, int256 amount0, int256 amount1, uint160 sqrtPriceX96, uint128 liquidity, int24 tick, uint128 protocolFeesToken0, uint128 protocolFeesToken1)